services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: "postgres-projeto-fiap-2023-Q1-64"
    ports:
      - "5432:5432"
    restart: always
  projeto-fiap:
    image: projeto-fiap:latest
    environment:
      - "SPRING_CONFIG_ADDITIONAL_LOCATION=classpath:application-docker.properties"
    build:
      context: "."
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db