apiVersion: v1
kind: Service
metadata:
  labels:
    app: lb-app-projetofiap
  name: lb-app-projetofiap
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: projetofiap-deployment
  type: LoadBalancer