name: "Docker Image Deploy"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Setup Maven and JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    
    # Install aws cli v2
    - name: AWS CLI
      run:  |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
            unzip -q /tmp/awscliv2.zip -d /tmp
            rm /tmp/awscliv2.zip
            sudo /tmp/aws/install --update
            rm -rf /tmp/aws/         
            aws --version

    # Install kubectl
    - name: kubectl
      run:  |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl version --client

    # Set up kubeconfig file
    - name: Kubeconfig setup
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        CLUSTER_NAME: 'projeto-fiap'
      run:  |
            echo $CLUSTER_NAME
            echo $AWS_DEFAULT_REGION
            echo $AWS_ACCESS_KEY_ID
            aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME

    # Maven build
    #- name: Build with Maven
    #  run: mvn package -Dmaven.test.skip

            
    # Build docker image and push to ecr
    #- name: AWS ECR
    #  uses: kciter/aws-ecr-action@v4
    #  with:
    #    access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    secret_access_key: ${{ secrets.AWS_ACCESS_KEY }}
    #    account_id: ${{ secrets.AWS_ACCOUNT_ID }}
    #    repo: projeto-fiap
    #    region: us-east-1
    #    create_repo: true

    # Set up kubeconfig file
    - name: Kubeconfig setup
      run:  |
            # kubectl apply -f ./entrega/kubernetes
            ls -l
